apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudflare-session-operator.fullname" . }}
  labels:
    {{- include "cloudflare-session-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cloudflare-session-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cloudflare-session-operator.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      automountServiceAccountToken: true
      serviceAccountName: {{ include "cloudflare-session-operator.serviceAccountName" . }}
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--metrics-bind-address=:{{ .Values.containerPort }}"
            - "--health-probe-bind-address=:{{ .Values.probePort }}"
            {{- if .Values.leaderElection.enabled }}
            - "--leader-elect=true"
            {{- end }}
          ports:
            - name: metrics
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
            - name: health
              containerPort: {{ .Values.probePort }}
              protocol: TCP
          env:
            {{- toYaml .Values.env | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.healthProbes.readinessPath }}
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: {{ .Values.healthProbes.livenessPath }}
              port: health
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
