{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cloudflare-session-operator.fullname" . }}
  labels:
    release: prometheus
    {{- include "cloudflare-session-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "cloudflare-session-operator.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}
